### ISSUE TITLE
Wrong desktop directory

### ISSUE THREAD

**Issue by TheSoulrester** [damienvanrobaeys/Run-in-Sandbox#1]
Hey, how is it possible to change the direcotry of the desktop?

my default desktop directory is located at the drive letter f
![explorer_rr9yDgHP8i](https://user-images.githubusercontent.com/7083599/79965152-f8efb100-848b-11ea-95d5-a11fafc7195b.png)

but every sandbox file will be created at drive letter c under users
![explorer_mgpIJ0JGvn](https://user-images.githubusercontent.com/7083599/79965288-2177ab00-848c-11ea-8f3a-6374b8a53e1c.png)

**Comment by damienvanrobaeys** [comment]
Hello, indeed this is a case I thought it wouldn't appear lol.
So your desktop is redirected to F:\dektop right ?

I will check that and keep you informed.

**Comment by TheSoulrester** [comment]
yes, my desktop is located at F:\MyName\desktop ;)

it was also changed due to the windows feature like it is mentioned here: https://windowsreport.com/change-download-location-windows-8-windows-10/

thank you ;)

**Comment by damienvanrobaeys** [comment]
I will add an entry in xml Sandbox_Config.xml to allow user to add where to save the wsb file.
Would it be ok for you?

**Comment by TheSoulrester** [comment]
That would be awesome <3 thanks ;)

**Comment by damienvanrobaeys** [comment]
ok, will proceed like that and keep you informed. Thx for the feedback :-)

**Comment by damienvanrobaeys** [comment]
I updated the Sandbox_Config.xml and RunInSandbox.ps1
In the XML I added a node <WSB_Location>Default</WSB_Location>

- If default the WSB will be saved on the desktop
- To save it somewhere else just add your own path like F:\Desktop

Could you please keep me informed if that works for you ?

**Comment by TheSoulrester** [comment]
Thank you 4 ur fast support.

4 now, it isn't working as expected.

i changed the "default" to my dir path

> <WSB_Location>F:\MyName\Desktop</WSB_Location>

also also tried out with double quotes

> <WSB_Location>"F:\MyName\Desktop"</WSB_Location>

but both didn't work :)

**Comment by damienvanrobaeys** [comment]
Have you replaced files Sandbox_Config.xml and RunInSandbox.ps1 from programdata with the new one ?

**Comment by TheSoulrester** [comment]
first i run Remove_Structure.ps1

after that, i was running Add_Structure.ps1 again ;)

**Comment by TheSoulrester** [comment]
oh, i see. you only did changes in RunInSandbox.ps1

**Comment by damienvanrobaeys** [comment]
Yes i changed RunInSandbox.ps1 and xml file. I also use remove structure then add again.
I configured the WSG_Location to c:\test.
If I run the context menu for istance from an EXE the wsb file is correctly created in c:\test.

**Comment by TheSoulrester** [comment]
![explorer_S8Mc9Uawpr](https://user-images.githubusercontent.com/7083599/79988283-c0ad9a00-84ae-11ea-9107-d5c303c1a92b.png)
![explorer_ZWRbI5DG4J](https://user-images.githubusercontent.com/7083599/79988285-c1463080-84ae-11ea-9f27-80be275c8a9d.png)
![notepad++_suGRyDegES](https://user-images.githubusercontent.com/7083599/79988293-c2775d80-84ae-11ea-91c1-bec09e3dae56.png)


hm, now i tried out another folder on c: but this also didnt work

maybe, Remove_Structure.ps1 does not remove necessary files?

what do i have to remove manually?

**Comment by damienvanrobaeys** [comment]
Could you please check the C:\ProgramData\Run_in_Sandbox\RunInSandbox.ps1 ?
You should have 
![image](https://user-images.githubusercontent.com/8832278/79990558-7da0f600-84b1-11ea-8d8c-6b38e383c4b4.png)

**Comment by TheSoulrester** [comment]
hm, ok this folder is not available, so it has been completly removed

**Comment by damienvanrobaeys** [comment]
Have you tested again after add_structure.ps1 ?

**Comment by TheSoulrester** [comment]
![notepad++_dpGH5Fsamb](https://user-images.githubusercontent.com/7083599/80007437-89e37e00-84c6-11ea-8cc7-63c6f556342b.png)

It seems that while using add_structure.ps1 a wrong RunInSandbox.ps1 will be copied to C:\ProgramData\Run_in_Sandbox because your if condition mentioned above is not available in C:\ProgramData\Run_in_Sandbox\RunInSandbox.ps1

**Comment by damienvanrobaeys** [comment]
Ohhhh my bad i uploaded the runinsandbox.ps1 at the root instead of the Run_in_sandbox folder

**Comment by damienvanrobaeys** [comment]
I tested after download once again the zip and now that works.
Before I had the same issue than you.
It was because I uploaded the main ps1 at the wrong place.

**Comment by TheSoulrester** [comment]
thank you ;)

everything seems fine now :)

**Comment by damienvanrobaeys** [comment]
Good news 😁
Thanks for the feedback

**Comment by damienvanrobaeys** [comment]
Fyi I just added a new functionnality that allows you to extract ZIP file directly in a sandbox

**Comment by TheSoulrester** [comment]
awesome! thank you ;)
