### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by LocalsGitHub** [damienvanrobaeys/Run-in-Sandbox#12]
Thank you so much for updating this project, I got it working. I have a question though. A window pops up asking "type switches to add", and Im not sure what it means. if I press the plus icon or close it, it still continues with running the file in the sandbox. Just curious as to what it does.
![powershell_O9SvUpwA5D](https://user-images.githubusercontent.com/76016636/126346463-4c749e83-e9c6-422f-8fb3-11306ed384e7.png)

**Comment by damienvanrobaeys** [comment]
Thank you for your feedback. You are trying to run a msi or exe right ?
The GUI allows you to a silent switch for the installation.

**Comment by damienvanrobaeys** [comment]
For more understanding, I changed the GUI as below:
![image](https://user-images.githubusercontent.com/8832278/126439672-ab36695a-2e9e-42ed-8027-69419ce35aff.png)

**Comment by LocalsGitHub** [comment]
Sorry but what is a "silent switch", or a "silent install"?

**Comment by damienvanrobaeys** [comment]
It is a switch allowing you to install an application without user interaction  like /q or /qn. This will install the app un background.

**Comment by LocalsGitHub** [comment]
Ah thanks!
