### ISSUE TITLE
Can't upgrade

### ISSUE THREAD

**Issue by DanielSjogren** [damienvanrobaeys/Run-in-Sandbox#14]
When attempting to install a newer version, it will halt during the Export_Reg_Config as the "reg export" doesn't have the /y parameter to overwrite existing files.

**Comment by damienvanrobaeys** [comment]
> When attempting to install a newer version, it will halt during the Export_Reg_Config as the "reg export" doesn't have the /y parameter to overwrite existing files.

Thanks for the feedback.
I will resolve that in the next version very soon.

**Comment by ccatlett1984** [comment]
I have a pull request in, that resolves this.

https://github.com/damienvanrobaeys/Run-in-Sandbox/pull/17

**Comment by damienvanrobaeys** [comment]
I added an overwrite on existing file which was the issue
