### ISSUE TITLE
Error 0x80072746

### ISSUE THREAD

**Issue by alessiodeia** [damienvanrobaeys/Run-in-Sandbox#15]
Installed on Win 10 pro for Workstation.
I can launch standalone Sandbox no problem, but when i use this tool via contex menu on PS1 files, EXE files ect. i get this error with the message "Lost connection to the Sandbox".
Am i doing something wrong?

**Comment by damienvanrobaeys** [comment]
Could you please send me WSB file generated ? 
You can send it at damien.vanrobaeys@gmail.com

**Comment by alessiodeia** [comment]
where can i find this file?

**Comment by damienvanrobaeys** [comment]
It should be on desktop or in %temp%

**Comment by toffe82** [comment]
Hello, 
I have the same problem on a brand new installation of WIN10, last version of the files downloaded today
I had it working fine on an old install.
I was testing opening notepad.
This is the wsb file :
<Configuration>
<VGpu>Enable</VGpu>
<Networking>Enable</Networking>
<AudioInput>Default</AudioInput>
<VideoInput>Default</VideoInput>
<ProtectedClient>Default</ProtectedClient>
<PrinterRedirection>Default</PrinterRedirection>
<ClipboardRedirection>Default</ClipboardRedirection>
<MemoryInMB></MemoryInMB>
<MappedFolders>
<MappedFolder>
<HostFolder>C:\WINDOWS\system32</HostFolder>
<ReadOnly>true</ReadOnly>
</MappedFolder>
</MappedFolders>
<LogonCommand>
<Command>C:\Users\WDAGUtilityAccount\Desktop\system32\notepad.exe </Command>
</LogonCommand>
</Configuration>

Any idea of what is wrong ?
Thank you

**Comment by toffe82** [comment]
`<Configuration>
<VGpu>Enable</VGpu>
<Networking>Enable</Networking>
<AudioInput>Default</AudioInput>
<VideoInput>Default</VideoInput>
<ProtectedClient>Default</ProtectedClient>
<PrinterRedirection>Default</PrinterRedirection>
<ClipboardRedirection>Default</ClipboardRedirection>
<MemoryInMB></MemoryInMB>
<MappedFolders>
<MappedFolder>
<HostFolder>C:\WINDOWS\system32</HostFolder>
<ReadOnly>true</ReadOnly>
</MappedFolder>
</MappedFolders>
<LogonCommand>
<Command>C:\Users\WDAGUtilityAccount\Desktop\system32\notepad.exe </Command>
</LogonCommand>
</Configuration>`

Sorry this is the file

**Comment by damienvanrobaeys** [comment]
Hi,
Just tested from the right-click menu and also using your WSB file and I have no error.
What is the windows 10 version you're using ?

**Comment by toffe82** [comment]
Hello,

It is win10 Pro 21h1 with all the update to this day: Microsoft Windows
[Version 10.0.19043.1288].
Copy and paste the program in the sandbox works.

???

Christophe

**Comment by damienvanrobaeys** [comment]
What do you mean by copy and paste program un sandbox ?
I used your wsb and ran it

**Comment by toffe82** [comment]
If I copy a program I want to test in the sandbox, it is working, so the
sandbox is working.
If I right-click to select run in sandbox, I have the error, same thing if
I double-click on the wsb file

Christophe

**Comment by damienvanrobaeys** [comment]
Ok it is working for me too.
Strange thing is that your wsb file works for me.
I will do some tests.

**Comment by damienvanrobaeys** [comment]
Your OS is an English version ?

**Comment by toffe82** [comment]
Yes it is the US version

**Comment by damienvanrobaeys** [comment]
Just installed a W10 pro for workstation on a VM then sandbox and runinsandbox.
No issue while right-click on notepad.exe then run in sandbox.
I'm updating the VM with latest CU and updates.

**Comment by toffe82** [comment]
This is the windows features installed
[image: image.png]
I have VMware workstation 16 installed too

**Comment by damienvanrobaeys** [comment]
and what is the result if you create a wsb as mentioned there ?
https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-configure-using-wsb-file

WSB below:
<Configuration>
  <VGpu>Disable</VGpu>
  <Networking>Disable</Networking>
  <MappedFolders>
    <MappedFolder>
      <HostFolder>C:\Users\Public\Downloads</HostFolder>
      <SandboxFolder>C:\Users\WDAGUtilityAccount\Downloads</SandboxFolder>
      <ReadOnly>true</ReadOnly>
    </MappedFolder>
  </MappedFolders>
  <LogonCommand>
    <Command>explorer.exe C:\users\WDAGUtilityAccount\Downloads</Command>
  </LogonCommand>
</Configuration>

**Comment by toffe82** [comment]
The download wsb works.
I made some test disabling options and if I disable VGpu, it works

My computer is a DELL XPS9560 with an nvidia GTX1050 and intel HD graphics
630

**Comment by damienvanrobaeys** [comment]
You mean the notepad wsb ? It means the option vgpu doesn't work on your device ?

**Comment by toffe82** [comment]
yes, notepad wsb works if I disable vgpu

**Comment by damienvanrobaeys** [comment]
And if you enable vgpu in download wsb ?

**Comment by toffe82** [comment]
If I enable vgpu in the download wsb, same error

**Comment by damienvanrobaeys** [comment]
Ok cool so the issue is mostly relative to sandbox and vgpu, nice feedback Christophe

**Comment by toffe82** [comment]
I find this :
https://www.tenforums.com/tutorials/159840-enable-disable-vgpu-sharing-windows-sandbox-windows-10-a.html

But there is nowhere on my install to find this settings, no sandbox in the
group policy ??
Can you check on your install ?

**Comment by damienvanrobaeys** [comment]
I will check that tomorrow, just shutdown laptop lol.
I will keep you informed

**Comment by damienvanrobaeys** [comment]
Actually the policy is to enable it by default but when you run the wsb it does the same for a specific sandbox session.
According to me it is mostly something relative to your device and option vgpu.
There are some posts about that:

https://answers.microsoft.com/en-us/windows/forum/all/windows-10-sandbox-vgpu-support-requirements/3e578858-c733-48c5-92ce-22fc58860446

**Comment by damienvanrobaeys** [comment]
https://www.reddit.com/r/sysadmin/comments/n9805y/gpu_passthrough_isnt_working_in_windows_sandbox/?utm_source=amp&utm_medium=&utm_content=post_body

**Comment by toffe82** [comment]
I don't have the option in the bios

**Comment by damienvanrobaeys** [comment]
As we have seen the issue is relative to native Windows Sandbox using different graphic cards and the option VGpu from WSB file.

For this issue, the solution should be:
- Open file Sources\Run_in_Sandbox\Sandbox_Config.xml
- Set value <VGpu>Enable</VGpu> to Default or Disable
- Run Add_Structure.ps1
