### ISSUE TITLE
Modifying Registry

### ISSUE THREAD

**Issue by matt-laird** [damienvanrobaeys/Run-in-Sandbox#2]
Would be great if you could implement a backup of the registry entries before imparting the changes. Changes to the `.exe` can cause some instability and confusion if it goes wrong.

**Comment by Uberck** [comment]
Yes, this is a great idea, the script completely messed up .exe associations and made the script look like a virus, couldn't launch anything.

**Comment by TemhAAhmeT** [comment]
Luckly i had system restore from yesterday :D.
Every exe was starting with sandbox. even i couldnt run regedit to fix :D
wasnt so misirable till 90s 🗡️ 
really great virus written by the coder.

**Comment by damienvanrobaeys** [comment]
Hello
Thanks for your feedback and sorry for the issue.
I was on vacation.
I did not have this kind of behavior. If i correctly understand when you run  random exe with double click it runs by default with sandbox ?

**Comment by damienvanrobaeys** [comment]
> Yes, this is a great idea, the script completely messed up .exe associations and made the script look like a virus, couldn't launch anything. Also, why in the world is the language fr-fr by default????

Hello, regarding the fr-fr, it was a mistake from my side, as i am french and forget to set it to en-us by default.
Regarding the exe issue, i'm currently workig on it. Could you please tell my what is your os build version ?
