### ISSUE TITLE
$Form PS1.close() error when testing .intunewin package

### ISSUE THREAD

**Issue by HarmVeenstra** [damienvanrobaeys/Run-in-Sandbox#20]
After Right-Clicking a .intunewin package and specifying the install command, the error below shows and disappears but everything does work like it should.

Exception calling "close" with "g argument(s): "Cannot set Visibility to Visible or call Show, Showbialog, close, or WindowInteropHelper. EnsureHandle while a window is closing." At C:\ProgramData Run_in_Sandbox\RunInSandbox.ps1:108 char:4

$Form PS1.close()

CategoryInfo

: NotSpecified: (:) [J, MethodInvocation Exception +FullyQualifiedErrorid : InvalidoperationException

**Comment by damienvanrobaeys** [comment]
Yep actually this is not really an error but I will hide it.
