### ISSUE TITLE
Run CMD/BAT as user or system in Sandbox

### ISSUE THREAD

**Issue by KnifMelti** [damienvanrobaeys/Run-in-Sandbox#21]
A context menu for this native/traditional shell (with or without parameters) would be nice to have for all of us who are dinosaurs! ;)

Also, a Cancel method if you change your mind after executing the parameters entry (and that goes for all of them)...

...loving your work with this @damienvanrobaeys 💯

**Comment by damienvanrobaeys** [comment]
Yep you're right.
I'm working on it.
Thanks for the feedback :-)

**Comment by damienvanrobaeys** [comment]
This will be integrated in the next version coming next week
