### ISSUE TITLE
WIndows Sandbox configuration file error

### ISSUE THREAD

**Issue by Charbird** [damienvanrobaeys/Run-in-Sandbox#24]
Hello,

When I try launching Run in Sandbox I'm getting a Windows Sandbox error stating "The configuration file was invalid. Error 0xc00cee2b." Windows Sandbox does work on my system and also tried disabling the GPU option in the config XML however that did not make a difference.

**Comment by damienvanrobaeys** [comment]
Not sure but I think it's relative to the vgpu option in Sandbox.
This is an error even with basic Windoows Sandbox.
You can try to reproduce it by creating a simple WSB file without using runinsandbox, set vgpu to enable and see if you have the error.
To solve it set vgpu to disable.

See the old issue below:
https://github.com/damienvanrobaeys/Run-in-Sandbox/issues/15
