### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by REEZDAB** [damienvanrobaeys/Run-in-Sandbox#3]
How do i remove the software?

**Comment by Uberck** [comment]
You have to reset the file extensions, since the registry isn't backed up in the process, best way to do this is by importing new .reg settings for the files you want, check here:
https://www.tenforums.com/tutorials/8703-restore-default-file-type-associations-windows-10-a.html

**Comment by damienvanrobaeys** [comment]
I will upload the add_structure file to backup regustry before.
I will then upload the remove_structure file to remove context menus.
