### ISSUE TITLE
Discussions about new features and questions

### ISSUE THREAD

**Issue by Joly0** [damienvanrobaeys/Run-in-Sandbox#33]
Hey, as discussions is not enabled in this repo, i am opening up an issue ticket for this.
There are a few things i´d like to know and maybe you can answer them.

- I saw you have added back psexec, but didnt add any code to the project to use pexec, is this intended?
- Otherwise, as i said in another issue, i have fixed the issues (hopefully all of them) regarding running psexec in sandbox and could open a pr for it, if needed?
- Could you please explain your indentation style to me? Its very very odd imo and not according to best practices. Not that i follow best practices myself all the time, but i still, for example, brackets should have the same indentation as the if/else/foreach/whatever statement and then the code between the brackets should only be indented. But maybe you could explain, why you do it like this and i could better understand it. But just wanted to mention, thats it very odd to read for me.

I really like this project and use it quite often now and really want to help it improve.

Maybe you could open up a discussion, so ifnew things can be discussed, then there is a place to do so and one wouldnt have to open up an issue for it

**Comment by damienvanrobaeys** [comment]
Just added Discussions :-)
