### ISSUE TITLE
Sandbox constantly refreshing

### ISSUE THREAD

**Issue by danzulfic** [damienvanrobaeys/Run-in-Sandbox#38]
Loving the features included in this tool. An issue I'm running into is that if I use sandbox from your tool, it constantly refreshes the sandbox and closes all open windows. If I run sandbox natively it does not refresh at all. Any ideas of what may be causing the issue?

**Comment by Joly0** [comment]
Hey, could you maybe elaborate a bit clearer what you mean by "it constantly refreshes the sandbox"? I have unfortunately no clue what you mean with this and i have never seen anything that would come close to your description ever

**Comment by danzulfic** [comment]
Just going to update this with a final note. I've updated to Windows 11 to test some features. The Sandbox isn't refreshing any longer in Windows 11.
