### ISSUE TITLE
Trash wbs file after closing sandbox

### ISSUE THREAD

**Issue by Uberck** [damienvanrobaeys/Run-in-Sandbox#4]
Anyway to do this so wbs files aren't left all over the place after running something in SandBox?

**Comment by damienvanrobaeys** [comment]
I will give it a look

**Comment by akuropka** [comment]
Actually I think it is convenient to keep the file since you can just start over or check details in case something goes wrong.
In my case the wsb files are saved in the temp folder.

**Comment by damienvanrobaeys** [comment]
You're right.
I think I will add a setting to change in the sandbox_config.xml to choose to keep wsb files or run it in memory.

**Comment by damienvanrobaeys** [comment]
this will be implemented in the next version coming next week
