### ISSUE TITLE
7zip support for zip files

### ISSUE THREAD

**Issue by Uberck** [damienvanrobaeys/Run-in-Sandbox#5]
Any way to add 7zip support for zip files?

**Comment by damienvanrobaeys** [comment]
Will give it a look.

**Comment by damienvanrobaeys** [comment]
Hello, sorry for the late feedback.
What is the need for 7zip support ? Extract content in sandbox with 7Zip ?

**Comment by damienvanrobaeys** [comment]
This will be implemented in the next version very soon
There will be a Run the 7z file after doing a right-click on 7z file.
