### ISSUE TITLE
Wrong Language Installed

### ISSUE THREAD

**Issue by ThisOneIsForPosting** [damienvanrobaeys/Run-in-Sandbox#6]
After completing PowerShell installation, all context menus are in the French language instead of my system default English. Is there a way to change the language once installed or will I need to reset file types and reinstall again but with all other languages deleted in the "Language_XML" folder except for "Language_en-US.xml"?  Thanks.

**Comment by valsamis-d** [comment]
@ThisOneIsForPosting 

I think we both made the same mistake: didn't read the notes completely before installing :)

First, you need to change _<Main_Language>_ in **Sources\Run_in_Sandbox\Sandbox_Config.xml** to:

_<Main_Language>**en-us**</Main_Language>_

Then redo the installation to have your content menus in English

And finally, remove French context menus:

_Reg.exe delete "HKLM\SOFTWARE\Classes\Microsoft.PowerShellScript.1\Shell\Exécuter le PS1 dans Sandbox" /f
Reg.exe delete "HKLM\SOFTWARE\Classes\Microsoft.PowerShellScript.1\Shell\Exécuter le PS1 dans Sandbox avec des paramètres" /f
Reg.exe delete "HKLM\SOFTWARE\Classes\VBSFile\Shell\Exécuter le VBS dans Sandbox" /f
Reg.exe delete "HKLM\SOFTWARE\Classes\VBSFile\Shell\Exécuter le VBS dans Sandbox avec des paramètres" /f
Reg.exe delete "HKLM\SOFTWARE\Classes\exefile\shell\Exécuter l'EXE dans Sandbox" /f
Reg.exe delete "HKLM\SOFTWARE\Classes\Msi.Package\shell\Exécuter le MSI dans Sandbox" /f_

This is what I did to fix mine. Hope it works for you as well :)

More info on: [Run file in Windows Sandbox from right-click and Context menu](http://www.systanddeploy.com/2019/06/run-file-in-windows-sandbox-from-right.html)

**Comment by ThisOneIsForPosting** [comment]
@valsamis-d 

Thank you for helping out with my mistake, much appreciated.  

Any chance you know how to resolve folders not opening by double-clicking?  I ran the folder.reg file to restore default file associations, and I can successfully right-click to open folders, but double-clicking still gives me the usual error message "This file does not have an app associated with it..."

**Comment by ThisOneIsForPosting** [comment]
@valsamis-d 
Fixed my problem. I downloaded and merged the DIRECTORY.reg file and all folders are accessible via double-click.
Thanks again for your help with my error on the language install. 
All issues closed.

**Comment by damienvanrobaeys** [comment]
Hello,
Sorry I was on vacation.
My bad, i copy the bad file (this one I used as I'm french).
I changed the sandbox_config.xml file to set by default to english.
