### ISSUE TITLE
Could not load file or assembly Operation is not supported

### ISSUE THREAD

**Issue by SylveonBottle** [damienvanrobaeys/Run-in-Sandbox#8]
Error is received when attempting to open .exe files.

![uvppNhNb48](https://user-images.githubusercontent.com/17802843/91050847-dd84e600-e5e4-11ea-97be-cbaee6f2cf58.png)

Fix for me: 
Navigate to `C:\ProgramData\Run_in_Sandbox\assembly`, right-click files, and unblock. 

https://stackoverflow.com/questions/34400546/could-not-load-file-or-assembly-operation-is-not-supported-exception-from-hres

I am unsure how to reproduce this issue or what caused it, but it might be worth putting this error + fix in a FAQ or potential fix/issues.

**Comment by damienvanrobaeys** [comment]
So you have this once you try to run random exe from right click in sandbox ?
This is a known issue after downloading file from the web. You can unblock a folder by doing gci yourfolder -recurse | unblock-file
This is a nice feedback too, i will implement it in the main script.

**Comment by damienvanrobaeys** [comment]
I added this in the new script that I will upload and indicates this in the how to guide.
Thanks for the feedback.
