### ISSUE TITLE
Missing files in repo

### ISSUE THREAD

**Issue by ICDeadPpl** [damienvanrobaeys/Run-in-Sandbox#9]
This repo doesn't contain the files "Add_Structure.ps1" and "Remove_Structure.ps1", which the README.MD says should be there.
Check screenshots:
![Annotation 2020-08-25 074427](https://user-images.githubusercontent.com/357885/91127675-04a3ec00-e6a7-11ea-886f-f4d87264d066.png)
![Annotation 2020-08-25 074344](https://user-images.githubusercontent.com/357885/91127683-0a99cd00-e6a7-11ea-8f52-1bdc477feee5.png)

**Comment by damienvanrobaeys** [comment]
Indeed, I'm working on somes bugs, I will upload them again in the week.
I will keep you informed in this issue.

**Comment by espanafly** [comment]
Could the solution be put the script in the %APPDATA%\Microsoft\Windows\SendTo\ location and then direct PS1, VBS, EXE, MSI to the %APPDATA%\Microsoft\Windows\SendTo\RunInSandbox.ps1
Not as fancy as universal right-click, but maybe safer?

**Comment by freak69ize** [comment]
Oh man needing this bad.... hope it gets fixed soon

**Comment by Nox13last** [comment]
How's it going. @damienvanrobaeys?

**Comment by FSCorrupt** [comment]
Hey @damienvanrobaeys 
The Files are still missing...

RG

**Comment by helight59** [comment]
repo abandoned?

**Comment by damienvanrobaeys** [comment]
Nope. Sorry i was a bit busy on some other subjects.
I have the new version finished but have to do some more tests.
Would you be interested ?

**Comment by ElPistoler0** [comment]
Me! I'm interested, me!

I was able to install an older full version, would like to upgrade it to the latest, please sir.

Thank you!

**Comment by Nox13last** [comment]
I don't know enough about Powershell to be able to debug any problems I come across, but I know a fair bit about annoying things by poking them in certain ways, and writing down what happens and how other people could annoy the thing in the same way.
Or, as boring people call it, "repro".

**Comment by chelbea** [comment]
It would be great if you make this version or the one you are working on it available.
Thanks!

**Comment by ruleil** [comment]
The files "Add_Structure.ps1" and "Remove_Structure.ps1" are still missing. Is it possible to add them back and add some comments in readme about the existing issues? Maybe someone of us can fix the existing issues.

**Comment by helight59** [comment]
Repo interested for me too! Just now app not working

**Comment by damienvanrobaeys** [comment]
Just uploaded missing files with more controls:
- Check if sources folder is there
- Check if all files are there
- Automatically unblock files
- Create a restore point
- 
If you have a test computer don't hesitate to test, before to test on your prod computer.
